# Generated by Django 5.0.1 on 2024-03-15 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_account_alter_booking_hotel'),
        ('hotel', '0002_hotel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='hotel.hotel'),
        ),
    ]
