# Generated by Django 5.0.1 on 2024-03-15 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_account_user'),
        ('review', '0002_alter_review_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='account.account'),
        ),
    ]
