# Generated by Django 5.0.1 on 2024-03-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_us',
            name='timestamp',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
