# Generated by Django 5.0.1 on 2024-03-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=70)),
                ('image', models.ImageField(upload_to='hotel/images')),
                ('price', models.DecimalField(decimal_places=0, max_digits=5)),
            ],
        ),
    ]
